### ISSUE TITLE
1

### ISSUE THREAD

**Issue by pengpeng-1572** [zeyang23/Formation-Control#1]
未定义函数或变量 'load_params'。

出错 demo_uav_formation (line 65)
params = load_params();

**Comment by zeyang23** [comment]
Sorry for the late reply. The function _load_params()_ is under _Formation-Control\uav-motion-control\dynamics\forward_dynamics_, you may add the whole folder _"Formation-control"_ into the path manually before running the codes.

**Comment by pengpeng-1572** [comment]
thank you so much for taking a time to answer my question,i have recognized&nbsp; it.



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 16, 2022 20:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zeyang23/Formation-Control] 1 (Issue #1)




 
Sorry for the late reply. The function load_params() is under Formation-Control\uav-motion-control\dynamics\forward_dynamics, you may add the whole folder "Formation-control" into the path manually before running the codes.
