### ISSUE TITLE
Time-varying formation control for unmanned aerial vehicles with switching interaction topologies

### ISSUE THREAD

**Issue by 123Lyyy** [zeyang23/Formation-Control#2]
1. May I ask which part of the code corresponds to the paper "Time-varying formation control for unmanned aerial vehicles with switching interaction topologies"?

2. When I want to get the graph in the **test** folder, the running error is reported, can you tell me the reason? As follows:
_like this_
  
![image](https://github.com/zeyang23/Formation-Control/assets/142013964/bec5ef89-f7e8-45f4-80e2-d5d3ec09e6df)

**Comment by zeyang23** [comment]
Hi~
Thanks for your interests on this repo.
1. The core code for _Time-varying formation control for unmanned aerial vehicles with switching interaction topologies_ is under the folder **time-varying formation tracking**.
2. Please add the full folder **Formation-Control** into the path of Matlab manually before running the code.
![image](https://github.com/zeyang23/Formation-Control/assets/50078363/6a754ca9-31b8-4337-8dd0-cce7cbe9ceee)

**Comment by 123Lyyy** [comment]
> Hi~ Thanks for your interests on this repo.
> 
> 1. The core code for _Time-varying formation control for unmanned aerial vehicles with switching interaction topologies_ is under the folder **time-varying formation tracking**.
> 2. Please add the full folder **Formation-Control** into the path of Matlab manually before running the code.
>    ![image](https://user-images.githubusercontent.com/50078363/260202271-6a754ca9-31b8-4337-8dd0-cce7cbe9ceee.png)

Thank you for your assistance and reply ! The above problems have been solved ! 

However, when I open the folder **time-varying formation tracking**, there are many folders and .m files, can you tell me which folder or .m file are highly consistent with the paper " Time-varying formation control for unmanned aerial vehicles with switching interaction topologies ''. I mean which file should I run firstly?
![042cb243b3222b9812a96ad961db62a](https://github.com/zeyang23/Formation-Control/assets/142013964/29bf9aac-6861-4b7e-ad71-4103db57d4ff)


Thanks!

**Comment by zeyang23** [comment]
You can run the **demo1.m** in the **test** folder, for which you will obtain the same results as the simulation of **example 2** in the paper _Time-varying formation control for unmanned aerial vehicles with switching interaction topologies_ (see Fig. 13).
![image](https://github.com/zeyang23/Formation-Control/assets/50078363/79ccc686-9744-45a4-8bd4-e5ee9f35d721)

**Comment by 123Lyyy** [comment]
> _Time-varying formation control for unmanned aerial vehicles with switching interaction topologies_

Thank you for your reply ! I am studying your code. 
By the way, except demo1.m in the test folder, whether the remaining simulations in 'Time-varying formation control for unmanned aerial vehicles with switching interaction topologies' can be run through other .m files.
